---
title: "Bias of Estimators_v2"
author: "Sadie Wisotsky"
date: "r format(Sys.time(), '%d %B %Y')"
output:
  html_document: default
  pdf_document:
    fig_caption: yes
    keep_tex: yes
header-includes:
- \usepackage{longtable}
- \usepackage{float}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(jsonlite)
library(ggplot2)
library(knitr)
library(stringr)
library(reshape2)
library(dplyr)
library(xtable)
library(tidyr)

compile <- function(cur.dir,csv){
  jsons <- list.files(path = cur.dir,
                      pattern = '*.json', recursive = TRUE)
  
  #create empty data.frame with variable names
  names = c("FILE", "BUSTED.LR", "BUSTED.SRV.LR", "BUSTED.omega3.MLE", "BUSTED.SRV.omega3.MLE", "BUSTED.omega3.prop",
            "BUSTED.SRV.omega3.prop", 'CV.SRV', 'BUSTED.P', 'BUSTED.SRV.P','BUSTED.AICc','BUSTED.SRV.AICc',
            'BUSTED.treelength' ,'BUSTED.SRV.treelength', 'Sites', 'Sequences', 
            'BUSTED.omega1.MLE','BUSTED.SRV.omega1.MLE', 'BUSTED.omega1.prop','BUSTED.SRV.omega1.prop',
            'BUSTED.omega2.MLE','BUSTED.SRV.omega2.MLE', 'BUSTED.omega2.prop','BUSTED.SRV.omega2.prop', 'SRV.alpha3.MLE',
            'SRV.alpha3.prop','SRV.alpha1.MLE','SRV.alpha1.prop','SRV.alpha2.MLE','SRV.alpha2.prop')
  
  classes = c("character", "numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric",
              "numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric",
              "numeric","numeric","numeric")
  df =read.table(text="", col.names = names, colClasses = classes)
  for (i in  seq(from=1, to=length(jsons), by=2)){
    filepath = paste(cur.dir,jsons[i], sep="")
    
    test = filepath %>% readLines() %>% gsub(x=.,pattern="nan",replacement ='"NA"') %>% fromJSON()
    
    
    
    FILE = jsons[i]
    Sites = length(test$profiles$unconstrained)
    tree_string = test$fits$`Unconstrained model`$`tree string`
    x= tree_string %>% str_replace_all("\\(",":") %>% str_replace_all("\\)",":") %>%     str_replace_all(",",":") %>% str_split(":")
    x= unlist(x)
    x =x[x !=""]
    br_len = matrix(x,ncol = 2,  byrow = T)
    colnames(br_len) = c("Branch", "Length")
    
    Sequences = sum(grepl("Node*", br_len[,1]) == FALSE)
    
    if (grepl("BUSTED-SRV",jsons[i])){
      filepath = paste(cur.dir,jsons[i], sep="")
      
      test = filepath %>% readLines() %>% gsub(x=.,pattern="nan",replacement ='"NA"') %>% fromJSON()      
      
      
      BUSTED.SRV.P = test$`test results`$p
      BUSTED.SRV.LR =test$`test results`$LR
      BUSTED.SRV.AICc = test$fits$`Unconstrained model`$`AIC-c`
      BUSTED.SRV.treelength = test$fits$`Unconstrained model`$`tree length`
      
      #OMEGA values for BUSTED.SRV
      BUSTED.SRV.omega3.MLE = test$fits$`Unconstrained model`$`rate distributions`$FG[3,1]
      BUSTED.SRV.omega3.prop = test$fits$`Unconstrained model`$`rate distributions`$FG[3,2]
      BUSTED.SRV.omega2.MLE = test$fits$`Unconstrained model`$`rate distributions`$FG[2,1]
      BUSTED.SRV.omega2.prop = test$fits$`Unconstrained model`$`rate distributions`$FG[2,2]
      BUSTED.SRV.omega1.MLE = test$fits$`Unconstrained model`$`rate distributions`$FG[1,1]
      BUSTED.SRV.omega1.prop = test$fits$`Unconstrained model`$`rate distributions`$FG[1,2]
      #ALPHA values for BUSTED.SRV
      SRV.alpha3.MLE = test$fits$`Unconstrained model`$`rate distributions`$SRV[3,1]
      SRV.alpha3.prop = test$fits$`Unconstrained model`$`rate distributions`$SRV[3,2]
      SRV.alpha2.MLE = test$fits$`Unconstrained model`$`rate distributions`$SRV[2,1]
      SRV.alpha2.prop = test$fits$`Unconstrained model`$`rate distributions`$SRV[2,2]
      SRV.alpha1.MLE = test$fits$`Unconstrained model`$`rate distributions`$SRV[1,1]
      SRV.alpha1.prop = test$fits$`Unconstrained model`$`rate distributions`$SRV[1,2]
      
      mom2 = SRV.alpha3.MLE^2*SRV.alpha3.prop+ SRV.alpha1.MLE^2*SRV.alpha1.prop+ SRV.alpha2.MLE^2*SRV.alpha2.prop
      mean= SRV.alpha3.MLE*SRV.alpha3.prop+ SRV.alpha1.MLE*SRV.alpha1.prop+ SRV.alpha2.MLE*SRV.alpha2.prop
      CV.SRV = sqrt(mom2-mean^2)/mean
      
    }
    if (grepl("BUSTED-SRV",jsons[i+1])==FALSE){
      filepath = paste(cur.dir,jsons[i+1], sep="")
      
      test = filepath %>% readLines() %>% gsub(x=.,pattern="nan",replacement ='"NA"') %>% fromJSON()    
      BUSTED.P = test$`test results`$p
      BUSTED.LR = test$`test results`$LR
      BUSTED.AICc = test$fits$`Unconstrained model`$`AIC-c`
      BUSTED.treelength = test$fits$`Unconstrained model`$`tree length`
      
      #OMEGA values for BUSTED
      BUSTED.omega3.MLE = test$fits$`Unconstrained model`$`rate distributions`$FG[3,1]
      BUSTED.omega3.prop = test$fits$`Unconstrained model`$`rate distributions`$FG[3,2]
      BUSTED.omega2.MLE = test$fits$`Unconstrained model`$`rate distributions`$FG[2,1]
      BUSTED.omega2.prop = test$fits$`Unconstrained model`$`rate distributions`$FG[2,2]
      BUSTED.omega1.MLE = test$fits$`Unconstrained model`$`rate distributions`$FG[1,1]
      BUSTED.omega1.prop = test$fits$`Unconstrained model`$`rate distributions`$FG[1,2]
      #ALPHA values for BUSTED
      #       BUSTED.alpha3.MLE = test$fits$`Unconstrained model`$`rate distributions`$SRV[3,1]
      #       BUSTED.alpha3.prop = test$fits$`Unconstrained model`$`rate distributions`$SRV[3,2]
      #       BUSTED.alpha2.MLE = test$fits$`Unconstrained model`$`rate distributions`$SRV[2,1]
      #       BUSTED.alpha2.prop = test$fits$`Unconstrained model`$`rate distributions`$SRV[2,2]
      #       BUSTED.alpha1.MLE = test$fits$`Unconstrained model`$`rate distributions`$SRV[1,1]
      #       BUSTED.alpha1.prop = test$fits$`Unconstrained model`$`rate distributions`$SRV[1,2]
      
    }
    
    df[nrow(df)+1,] <- c(FILE, BUSTED.LR, BUSTED.SRV.LR, BUSTED.omega3.MLE, BUSTED.SRV.omega3.MLE, BUSTED.omega3.prop,
                         BUSTED.SRV.omega3.prop, CV.SRV, BUSTED.P, BUSTED.SRV.P,BUSTED.AICc,BUSTED.SRV.AICc,
                         BUSTED.treelength ,BUSTED.SRV.treelength, Sites, Sequences, 
                         BUSTED.omega1.MLE,BUSTED.SRV.omega1.MLE, BUSTED.omega1.prop,BUSTED.SRV.omega1.prop,
                         BUSTED.omega2.MLE,BUSTED.SRV.omega2.MLE, BUSTED.omega2.prop,BUSTED.SRV.omega2.prop, SRV.alpha3.MLE,
                         SRV.alpha3.prop,SRV.alpha1.MLE,SRV.alpha1.prop,SRV.alpha2.MLE,SRV.alpha2.prop)
    
  }
  df[,2:30]=as.numeric(unlist(df[,2:30]))
  write.csv(file = csv, x = df, row.names= F)
  # return(df)
}

simulation_inputs <- function(dir,csv){
  require("stringr")
  require("jsonlite")
  require("dplyr")
  list = list.files(path = dir, recursive = T, pattern ="^([^.]+)$")
  #set up the empty data frame
  names = c("Sites" ,"Cat", "Omega 1 Rate", "Omega 2 Rate", "Omega 3 Rate", "Omega 1 Weight", "Omega 2 Weight", "Omega 3 Weight",
            "Alpha 1 Rate", "Alpha 2 Rate", "Alpha 3 Rate","Alpha 1 Weight", "Alpha 2 Weight", "Alpha 3 Weight")
  setup.tab = read.table(text = "",col.names = names)
  #loop thru each file to get info in correct format
  for(i in seq(from = 1, to= length(list))){
    x=readLines(paste(dir,list[i], sep = "/"))
    #making this a readable json
    x1 = str_replace(x,":\\{", ":\\[")
    
    x1[c(5:6,12:13)] = str_replace(x1[c(5:6,12:13)],"\\{([-+]?[0-9]*\\.?[0-9]+,[-+]?[0-9]*\\.?[0-9]+)\\}", "\\[\\1\\]," )
    
    x1[c(7,14)] = str_replace(x1[c(7,14)],"\\{([-+]?[0-9]*\\.?[0-9]+,[-+]?[0-9]*\\.?[0-9]+)\\}", "\\[\\1\\]" )
    x1[c(8,15)] = str_replace(x1[c(8,15)], "\\}", "\\]")
    r= fromJSON(x1)
    omega_rates = r$`omega distribution`[,1]
    names(omega_rates)= c("Omega 1 Rate", "Omega 2 Rate", "Omega 3 Rate")
    omega_weights = r$`omega distribution`[,2]
    names(omega_weights) = c("Omega 1 Weight", "Omega 2 Weight", "Omega 3 Weight")
    
    Alpha_rates = r$`alpha distribution`[,1]
    names(Alpha_rates)= c("Alpha 1 Rate", "Alpha 2 Rate", "Alpha 3 Rate")
    Alpha_weights = r$`alpha distribution`[,2]
    names(Alpha_weights) = c("Alpha 1 Weight", "Alpha 2 Weight", "Alpha 3 Weight")
    
    
    setup.tab[nrow(setup.tab)+1,] = c(r$sites,list[i], omega_rates,omega_weights,Alpha_rates,Alpha_weights)
  }
  setup.tab =select(setup.tab, Sites, Cat, Omega.1.value, Omega.1.Weight, Omega.2.value, Omega.2.Weight,Omega.3.value, Omega.3.Weight,
                    Alpha.1.value, Alpha.1.Weight, Alpha.2.value, Alpha.2.Weight,Alpha.3.value, Alpha.3.Weight)
  setup.tab[,3:14] = as.numeric(unlist(setup.tab[,3:14]))
  mom2 = setup.tab$Alpha.1.value^2*setup.tab$Alpha.1.Weight+setup.tab$Alpha.2.value^2*setup.tab$Alpha.2.Weight + setup.tab$Alpha.3.value^2*setup.tab$Alpha.3.Weight
  
  mean = setup.tab$Alpha.1.value*setup.tab$Alpha.1.Weight+setup.tab$Alpha.2.value*setup.tab$Alpha.2.Weight + setup.tab$Alpha.3.value*setup.tab$Alpha.3.Weight
  
  setup.tab = mutate(setup.tab,CV.SRV = sqrt(mom2-mean^2)/mean)
  
  #return(setup.tab)
  write.csv(file = csv, x = setup.tab, row.names= F)
}


add_truth <- function(dat, truth){
  dat = dat %>% mutate(True.CV = 1337)
  dat = dat %>% mutate(True.omega3.value = 8008)
  dat = dat %>% mutate(True.omega1.value = 8008)
  dat = dat %>% mutate(True.omega2.value = 8008)
  dat = dat %>% mutate(True.alpha3.value = 8008)
  dat = dat %>% mutate(True.alpha2.value = 8008)
  dat = dat %>% mutate(True.alpha1.value = 8008)
  dat = dat %>% mutate(True.omega3.prop = 8008)
  dat = dat %>% mutate(True.omega1.prop = 8008)
  dat = dat %>% mutate(True.omega2.prop = 8008)
  dat = dat %>% mutate(True.alpha3.prop = 8008)
  dat = dat %>% mutate(True.alpha2.prop = 8008)
  dat = dat %>% mutate(True.alpha1.prop = 8008)
  for( i in seq(from = 1, to = nrow(truth), by = 1)){
    temp = which(str_detect(dat$FILE,truth$Cat[i]))
    dat$True.CV[temp] = truth$CV.SRV[i] 
    dat$True.omega3.value[temp] = truth$Omega.3.value[i]
    dat$True.omega2.value[temp] = truth$Omega.2.value[i]
    dat$True.omega1.value[temp] = truth$Omega.1.value[i]
    dat$True.alpha1.value[temp] = truth$Alpha.1.value[i]
    dat$True.alpha2.value[temp] = truth$Alpha.2.value[i]
    dat$True.alpha3.value[temp] = truth$Alpha.3.value[i]
    dat$True.omega3.prop[temp] = truth$Omega.3.Weight[i]
    dat$True.omega2.prop[temp] = truth$Omega.2.Weight[i]
    dat$True.omega1.prop[temp] = truth$Omega.1.Weight[i]
    dat$True.alpha1.prop[temp] = truth$Alpha.1.Weight[i]
    dat$True.alpha2.prop[temp] = truth$Alpha.2.Weight[i]
    dat$True.alpha3.prop[temp] = truth$Alpha.3.Weight[i]
  }
  return(dat)
}



process_dat <- function(dir, basename){
  temp = paste(dir,basename,"_Truth.csv", sep = "")
  #simulation_inputs(dir,temp)
  truth = read.csv(temp, as.is = T)
  temp = paste(dir,basename,"_results.csv", sep = "")
  # compile(dir,temp)
  dat = read.csv(temp, as.is = T)
  dat = add_truth(dat, truth)
  dat = mutate(dat, Cat = str_extract(dat$FILE, "YesYes|YesNo|NoNo|NoYes"))
  dat$True.CV = round(dat$True.CV, 3)
  return(dat)
}


pwr_tab <- function(dat) {
  
  
  A1.dat = dat
  A1.basic = A1.dat %>% group_by(True.omega3.value, True.CV) %>% summarise(num_reps = n())
  
  A1.BUSTED = A1.dat %>% group_by(True.omega3.value,True.CV, Cat) %>% filter(BUSTED.P <
                                                                               0.05) %>% tally()
  A1.BUSTED = rename(A1.BUSTED, "BUSTED_PWR" = n)
  
  A1.SRV = A1.dat %>%  group_by(True.omega3.value, True.CV, Cat) %>% filter(BUSTED.SRV.P <
                                                                              0.05) %>%  tally()
  A1.SRV = rename(A1.SRV, "SRV_PWR" = n)
  
  A1.pwr.tab = full_join(A1.BUSTED, A1.SRV, by = c("True.omega3.value", "True.CV", "Cat")) %>% 
    full_join(., A1.basic, by = c("True.omega3.value", "True.CV"))
  
  
  
  A1.means = A1.dat %>% group_by(True.omega3.value) %>%   summarise(
    "$BUSTED \\omega_3$ MLE" = mean(BUSTED.omega3.MLE),
    "SRV $\\omega_3$ MLE" = mean(BUSTED.SRV.omega3.MLE),
    "Mean CV" = mean(CV.SRV)
  )
  A1.pwr.tab = full_join(A1.pwr.tab, A1.means, by = "True.omega3.value")
  A1.pwr.tab = replace(A1.pwr.tab, is.na(A1.pwr.tab), 0)
  A1.pwr.tab$BUSTED_PWR = A1.pwr.tab$BUSTED_PWR / A1.pwr.tab$num_reps
  A1.pwr.tab$SRV_PWR = A1.pwr.tab$SRV_PWR / A1.pwr.tab$num_reps
  return(A1.pwr.tab)
}
```

```{r get data, include= FALSE}

# dir= "G:/BRC/SimResults/Five_seq/"
# basename = "Five_seq_all"
# all.dat = process_dat(dir, basename)

all.dat.4 = read.csv("C:/Users/srwisots/Google Drive/Muse/BRC/SimResults/Five_seq/All_12_1_16_processed.csv", as.is= TRUE)

#old.all.dat = all.dat
all.dat = all.dat.4
YesYes_1000 = all.dat %>% filter(Sites == 1000, True.omega3.value >= 1.1, True.CV >= 0, True.CV != 1.031)

sub = YesYes_1000  %>% group_by(True.CV) %>% tally %>% filter(n > 500)
a =YesYes_1000 %>% filter(True.CV == sub$True.CV)
```

##Preliminary Graphs

graphs from the report updated

```{r, echo = FALSE, fig.cap="Power Versus the True $\\omega_3$ value for simulations. Grouped by the CV of SRV and the method used to analyze the replicates."}
a.pwr.tab = pwr_tab(a)
cl = colors()
a.pwr.tab %>% select(one_of(
c("True.omega3.value", "True.CV", "BUSTED_PWR", "SRV_PWR")
)) %>% melt(id.vars = c("True.omega3.value", "True.CV")) %>% ggplot(aes(
x = True.omega3.value,
y = value,
color = interaction(True.CV, variable, sep = " ")
)) +
geom_point() + geom_smooth() + labs(x = expression("True "*omega[3]), y = "Power", color = "CV and Analysis") 

```

```{r, echo = FALSE, fig.pos='H',fig.cap= "Showing how the power changes for both analysis as the amount of positive selection and CV of SRV inxrease. Each square represents 100 replicates simulated with the given values.The color corespond to the power analysis to correctly identify positive selection."}
temp=   a.pwr.tab %>% select(one_of(
  c("True.omega3.value", "True.CV", "BUSTED_PWR", "SRV_PWR")
)) %>% filter(True.omega3.value >= 1.1  && True.CV != 1.031) %>% melt(id.vars = c("True.omega3.value", "True.CV"))
temp %>% ggplot(aes(x=True.omega3.value, y = True.CV))+ geom_tile(aes(fill = value))+ facet_grid(~variable)+
  labs(x =expression("True "*omega[3]), y = "True CV of SRV", color = "Power")

```



--------------------

##tables and graphs for $\omega_1$ MLE and Proportion 

```{r table for omega1, message=FALSE, warning=FALSE, echo=FALSE, results="asis"}


omega1.bias = a %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("omega1")), funs(mean,median))

 b= omega1.bias %>% gather(key = test, value = estimate, - True.omega3.value, -True.CV, -True.omega1.value_mean, -True.omega1.prop_mean, -True.omega1.value_median, -True.omega1.prop_median) 

  b = ungroup(b) %>% mutate( analysis = str_extract(b$test,"BUSTED.SRV\\.|BUSTED\\.|True"))
 b = b %>% arrange(True.omega3.value)
 b = mutate(b, 
            stat = str_extract(b$test,"mean|median"), idk = str_extract(b$test, "MLE|prop"),
            thing = interaction(stat,idk))

# glimpse(b)
c = spread(select(b, -test, - stat, -idk), key = thing, value = estimate)

#rename some shit

c =c %>% rename(True.value.Mean =True.omega1.value_mean, True.Prop.Mean =True.omega1.prop_mean, 
             True.value.Median =True.omega1.value_median,True.Prop.Median =True.omega1.prop_median)
c = c %>% select(True.omega3.value, True.CV,analysis, mean.MLE, True.value.Mean, median.MLE,mean.prop,True.Prop.Mean,
                 median.prop)
# cnames = c(expression("True "*omega[3]), "True CV of SRV", "Method", expression("Mean MLE "*omega[1]),expression("True "*omega[1]), expression("Median MLE "*omega[1]), expression("Mean Prop "*omega[1]), expression("True prop "*omega[1]), expression("Median prop "*omega[1])
#            )

cnames = c("True $\\omega_3$", "True CV \n of SRV", "Method", "Mean MLE $\\omega_1$", "True $\\omega_1$", "Median MLE $\\omega_1$", "Mean prop $\\omega_1$", "True prop $\\omega_1$", "Median prop $\\omega_1$"           )

e= c %>% arrange(True.omega3.value) %>% filter(True.omega3.value %in% c(1.1,1.5,2,2.5,2.9))
colnames(e) <- cnames
add.to.row <- list(pos = list(0), command = NULL)
command <- paste0("\\hline\n\\endhead\n",
"\\hline\n",
"\\multicolumn{", dim(e)[2] , "}{l}",
"{\\footnotesize Continued on next page}\n",
"\\endfoot\n",
"\\endlastfoot\n")
add.to.row$command <- command

e.xtab = e%>% xtable(caption = "Table for $\\omega_1$ values.") 
align(e.xtab) = "r|lp{1cm}l|p{1.5cm}p{1.5cm}p{1.5cm}|p{1.5cm}p{1.5cm}p{1.5cm}|"
e.xtab%>% print( include.rownames = F, sanitize.text.function = function(x){x},  add.to.row = add.to.row,tabular.environment = 'longtable', floating = FALSE, type = 'html')

```


```{r graph for omega1, echo = FALSE, fig.cap="Bias of $\\omega_1$ value across increasing $\\omega_3$ values and facted by the analysis type used and the CV of SRV simulated with. The  green line is the value of $\\omega_1$ that all the replicates were simulated with, refered to as the true value. The orange and blue lines represent the mean and median of the $\\omega_1$ values as calulated at the given true $\\omega_3$ rate and CV of SRV by the labeled analysis. The CV values are indicated on the facets.This set up is used for the majority of the following figures."}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.MLE, True.value.Mean, median.MLE) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free") + labs(x = expression("True "*omega[3]), y = expression("Expected "*omega[1]))+scale_color_discrete(name = "Measure", breaks = c("mean.MLE", "True.value.Mean", "median.MLE"), 
                                                        labels = c("Mean MLE", expression("True "*omega[1]), "Median MLE"))
```

```{r, echo =FALSE, fig.cap="Bias of $\\omega_1$ proportion. The green line is the proportion of sites that were simulated with the true $\\omega_1$ value. The orange line is the mean proportion of sites with $\\omega_1$, while the blue line is the median, according to the respective analysis. "}
d = c %>% select(True.omega3.value,True.CV, analysis,mean.prop, True.Prop.Mean, median.prop) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free") +labs(x = expression("True "*omega[3]), y = expression("Expected "*omega[1]*" prop"))+ scale_color_discrete(name = "Measure", breaks = c("mean.prop", "True.Prop.Mean", "median.prop"), labels = c("Mean prop", expression("True "*omega[1]*" prop"), "Median prop"))


```

-------------------------

##$\omega_2$

```{r table for omega2, message=FALSE, warning=FALSE, echo=FALSE, results="asis"}
omega2.bias = a %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("omega2")), funs(mean,median))

 b= omega2.bias %>% gather(key = test, value = estimate, -True.omega3.value,-True.CV, -True.omega2.value_mean, -True.omega2.prop_mean, -True.omega2.value_median, -True.omega2.prop_median)

  b =ungroup(b) %>% mutate( analysis = str_extract(b$test,"BUSTED.SRV\\.|BUSTED\\.|True"))
 b = b %>% arrange(True.omega3.value)
 b = mutate(b,
            stat = str_extract(b$test,"mean|median"), idk = str_extract(b$test, "MLE|prop"),
            thing = interaction(stat,idk))

 #glimpse(b)
c = spread(select(b, -test, - stat, -idk), key = thing, value = estimate)

#rename some shit

c =c %>% rename(True.value.Mean =True.omega2.value_mean, True.Prop.Mean =True.omega2.prop_mean,
             True.value.Median =True.omega2.value_median,True.Prop.Median =True.omega2.prop_median)
c = c %>% select(True.omega3.value, True.CV,analysis, mean.MLE, True.value.Mean, median.MLE,mean.prop,True.Prop.Mean,
                 median.prop)

cnames = c("True $\\omega_3$", "True CV of SRV", "Method", "Mean MLE $\\omega_2$", "True $\\omega_2$", "Median MLE $\\omega_2$", "Mean prop $\\omega_2$", "True prop $\\omega_2$", "Median prop $\\omega_2$"           )

e= c %>% arrange(True.omega3.value) %>% filter(True.omega3.value %in% c(1.1,1.5,2,2.5,2.9))
colnames(e) <- cnames

add.to.row <- list(pos = list(0), command = NULL)
command <- paste0("\\hline\n\\endhead\n",
"\\hline\n",
"\\multicolumn{", dim(e)[2] , "}{l}",
"{\\footnotesize Continued on next page}\n",
"\\endfoot\n",
"\\endlastfoot\n")
add.to.row$command <- command

e.xtab = e%>% xtable() 
align(e.xtab) = "r|lp{1cm}l|p{1.5cm}p{1.5cm}p{1.5cm}|p{1.5cm}p{1.5cm}p{1.5cm}|"
e.xtab%>% print( include.rownames = F, sanitize.text.function = function(x){x}, scalebox = .75,  add.to.row = add.to.row,tabular.environment = 'longtable', floating = FALSE, type = 'html')
```

```{r graph for omega2, echo = FALSE, fig.cap="The mean and median maximum likelihood estimates for $\\omega_2$ versus the true value."}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.MLE, True.value.Mean, median.MLE) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+ 
  labs(x = expression("True "*omega[3]), y = expression("Expected "*omega[2]))+
  scale_color_discrete(name = "Measure", breaks = c("mean.MLE", "True.value.Mean", "median.MLE"), labels = c("Mean MLE", expression("True "*omega[2]), "Median MLE"))
```


```{r, echo=FALSE, fig.cap="The mean and median proportion of sites with $\\omega_2$  versus the true proportion of sites simulated to have that value."}
d = c %>% select(True.omega3.value,True.CV, analysis,mean.prop, True.Prop.Mean, median.prop) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+labs(x = expression("True "*omega[3]), y = expression("Expected "*omega[2]))+ scale_color_discrete(name = "Measure", breaks = c("mean.prop", "True.Prop.Mean", "median.prop"), labels = c("Mean prop", expression("True "*omega[2]*" prop"), "Median prop"))


```

----------------------------------

##$\omega_3$

```{r table for omega3, message=FALSE, warning=FALSE, echo=FALSE, results="asis"}

omega3.bias = a %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("omega3")), funs(mean,median))

 b= omega3.bias %>% gather(key = test, value = estimate, -True.omega3.value,-True.CV, -True.omega3.prop_mean, -True.omega3.prop_median)

  b = ungroup(b) %>% mutate( analysis = str_extract(b$test,"BUSTED.SRV\\.|BUSTED\\.|True"))
 b = b %>% arrange(True.omega3.value)
 b = mutate(b,
            stat = str_extract(b$test,"mean|median"), idk = str_extract(b$test, "MLE|prop"),
            thing = interaction(stat,idk))

# glimpse(b)
c = spread(select(b, -test, - stat, -idk), key = thing, value = estimate)

#rename some shit

c =c %>% rename(True.Prop.Mean =True.omega3.prop_mean,
             True.Prop.Median =True.omega3.prop_median)
c = c %>% select(True.CV,analysis, mean.MLE, True.omega3.value, median.MLE,mean.prop,True.Prop.Mean,
                 median.prop)

cnames = c("True CV of SRV", "Method", "Mean MLE $\\omega_3$", "True $\\omega_3$", "Median MLE $\\omega_3$", "Mean prop $\\omega_3$", "True prop $\\omega_3$", "Median prop $\\omega_3$"           )

e= c %>% arrange(True.omega3.value) %>% filter(True.omega3.value %in% c(1.1,1.5,2,2.5,2.9))
colnames(e) <- cnames

add.to.row <- list(pos = list(0), command = NULL)
command <- paste0("\\hline\n\\endhead\n",
"\\hline\n",
"\\multicolumn{", dim(e)[2] , "}{l}",
"{\\footnotesize Continued on next page}\n",
"\\endfoot\n",
"\\endlastfoot\n")
add.to.row$command <- command

e.xtab = e%>% xtable()
align(e.xtab) = "r|p{1cm}l|p{1.5cm}p{1.5cm}p{1.5cm}|p{1.5cm}p{1.5cm}p{1.5cm}|"
e.xtab%>% print( include.rownames = F, sanitize.text.function = function(x){x}, scalebox = .75,  add.to.row = add.to.row,tabular.environment = 'longtable', floating = FALSE, type = "html")

```

```{r graph for omega3, echo = FALSE}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.MLE,  median.MLE) %>% mutate(True.value = True.omega3.value) %>% select(True.omega3.value,True.CV, analysis,mean.MLE, True.value, median.MLE) %>% 
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+ 
  labs(x = expression("True "*omega[3]), y = expression("Expected "*omega[3]))+
  scale_color_discrete(name = "Measure", breaks = c("mean.MLE","True.value", "median.MLE"), labels = c("Mean MLE", "Truth","Median MLE"))
```

```{r, echo = FALSE}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.prop, True.Prop.Mean, median.prop) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+
  labs(x = expression("True "*omega[3]), y = expression("Expected "*omega[3]*" prop"))+
  scale_color_discrete(name = "Measure", breaks = c("mean.prop", "True.Prop.Mean", "median.prop"), labels = c("Mean prop", expression("True "*omega[3]*" prop"), "Median prop"))


```

--------------------

##$\alpha_1$

```{r alpha1 table, message=FALSE, warning=FALSE, echo=FALSE, results="asis"}

alpha1.bias = a %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("alpha1")), funs(mean,median))

b= alpha1.bias %>% gather(key = test, value = estimate, -True.omega3.value,-True.CV, -True.alpha1.value_mean, -True.alpha1.prop_mean, -True.alpha1.value_median, -True.alpha1.prop_median)

b = ungroup(b) %>% mutate( analysis = str_extract(b$test,"SRV\\.|BUSTED\\.|True"))
b = b %>% arrange(True.omega3.value)
b = mutate(b,
           stat = str_extract(b$test,"mean|median"), idk = str_extract(b$test, "MLE|prop"),
           thing = interaction(stat,idk))

#glimpse(b)
c = spread(select(b, -test, - stat, -idk), key = thing, value = estimate)

#rename some shit

c =c %>% rename(True.value.Mean =True.alpha1.value_mean, True.Prop.Mean =True.alpha1.prop_mean,
                True.value.Median =True.alpha1.value_median,True.Prop.Median =True.alpha1.prop_median)
c = c %>% select(True.omega3.value, True.CV,analysis, mean.MLE, True.value.Mean, median.MLE,mean.prop,True.Prop.Mean,
                 median.prop)

cnames = c("True $\\omega_3$", "True CV of SRV", "Method", "Mean MLE $\\alpha_1$", "True $\\alpha_1$", "Median MLE $\\alpha_1$", "Mean prop $\\alpha_1$", "True prop $\\alpha_1$", "Median prop $\\alpha_1$")

e= c %>% arrange(True.omega3.value) %>% filter(True.omega3.value %in% c(1.1,1.5,2,2.5,2.9))
colnames(e) <- cnames
e.xtab = e%>% xtable()
align(e.xtab) = "r|lp{1cm}l|p{1.5cm}p{1.5cm}p{1.5cm}|p{1.5cm}p{1.5cm}p{1.5cm}|"
e.xtab%>% print( include.rownames = F, sanitize.text.function = function(x){x}, scalebox = .75,  add.to.row = add.to.row,tabular.environment = 'longtable', floating = FALSE, type = 'html')
```

```{r graph for alpha1, echo = FALSE}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.MLE, True.value.Mean, median.MLE) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free") + 
  labs(x = expression("True "*omega[3]), y = expression("Expected "*alpha[1]))+
  scale_color_discrete(name = "Measure", breaks = c("mean.MLE", "True.value.Mean", "median.MLE"), labels = c("Mean MLE", expression("True "*alpha[1]), "Median MLE"))
```

```{r, echo = FALSE}
d = c %>% select(True.omega3.value,True.CV, analysis,mean.prop, True.Prop.Mean, median.prop) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+
  labs(x = expression("True "*omega[3]), y = expression("Expected "*alpha[1]*" prop"))+
  scale_color_discrete(name = "Measure", breaks = c("mean.prop", "True.Prop.Mean", "median.prop"), labels = c("Mean prop", expression("True "*alpha[1]*" prop"), "Median prop"))

```

-------------

##$\alpha_2$

```{r alpha2 table, message=FALSE, warning=FALSE, echo=FALSE, results="asis"}
alpha2.bias = a %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("alpha2")), funs(mean,median))

b= alpha2.bias %>% gather(key = test, value = estimate, -True.omega3.value,-True.CV, -True.alpha2.value_mean, -True.alpha2.prop_mean, -True.alpha2.value_median, -True.alpha2.prop_median)

b = ungroup(b) %>% mutate( analysis = str_extract(b$test,"SRV\\.|BUSTED\\.|True"))
b = b %>% arrange(True.omega3.value)
b = mutate(b,
           stat = str_extract(b$test,"mean|median"), idk = str_extract(b$test, "MLE|prop"),
           thing = interaction(stat,idk))

#glimpse(b)
c = spread(select(b, -test, - stat, -idk), key = thing, value = estimate)

#rename some shit

c =c %>% rename(True.value.Mean =True.alpha2.value_mean, True.Prop.Mean =True.alpha2.prop_mean,
                True.value.Median =True.alpha2.value_median,True.Prop.Median =True.alpha2.prop_median)
c = c %>% select(True.omega3.value, True.CV ,analysis, mean.MLE, True.value.Mean, median.MLE,mean.prop,True.Prop.Mean,
                 median.prop)

cnames = c("True $\\omega_3$", "True CV of SRV", "Method", "Mean MLE $\\alpha_2$", "True $\\alpha_2$", "Median MLE $\\alpha_2$", "Mean prop $\\alpha_2$", "True prop $\\alpha_2$", "Median prop $\\alpha_2$")

e= c %>% arrange(True.omega3.value) %>% filter(True.omega3.value %in% c(1.1,1.5,2,2.5,2.9))
colnames(e) <- cnames
e.xtab = e%>% xtable()
align(e.xtab) = "r|lp{1cm}l|p{1.5cm}p{1.5cm}p{1.5cm}|p{1.5cm}p{1.5cm}p{1.5cm}|"
e.xtab%>% print( include.rownames = F, sanitize.text.function = function(x){x}, scalebox = .75,  add.to.row = add.to.row,tabular.environment = 'longtable', floating = FALSE, type = 'html')
```

```{r graph for alpha2, echo = FALSE}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.MLE, True.value.Mean, median.MLE) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+ 
  labs(x = expression("True "*omega[3]), y = expression("Expected "*alpha[2]))+
  scale_color_discrete(name = "Measure", breaks = c("mean.MLE", "True.value.Mean", "median.MLE"), labels = c("Mean MLE", expression("True "*alpha[2]), "Median MLE"))
```

```{r, echo=FALSE}
d = c %>% select(True.omega3.value,True.CV, analysis,mean.prop, True.Prop.Mean, median.prop) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+
  labs(x = expression("True "*omega[3]), y = expression("Expected "*alpha[2]*" prop"))+
  scale_color_discrete(name = "Measure", breaks = c("mean.prop", "True.Prop.Mean", "median.prop"), labels = c("Mean prop", expression("True "*alpha[2]*" prop"), "Median prop"))


```

------------

##$\alpha_3$

```{r alpha 3 table, message=FALSE, warning=FALSE, echo=FALSE, results="asis"}

alpha3.bias = a %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("alpha3")), funs(mean,median))

b= alpha3.bias %>% gather(key = test, value = estimate,-True.omega3.value, -True.CV, -True.alpha3.value_mean, -True.alpha3.prop_mean, -True.alpha3.value_median, -True.alpha3.prop_median)

b =ungroup(b) %>% mutate( analysis = str_extract(b$test,"SRV\\.|BUSTED\\.|True"))
b = b %>% arrange(True.omega3.value)
b = mutate(b,
           stat = str_extract(b$test,"mean|median"), idk = str_extract(b$test, "MLE|prop"),
           thing = interaction(stat,idk))

#glimpse(b)
c = spread(select(b, -test, - stat, -idk), key = thing, value = estimate)

#rename some shit

c =c %>% rename(True.value.Mean =True.alpha3.value_mean, True.Prop.Mean =True.alpha3.prop_mean,
                True.value.Median =True.alpha3.value_median,True.Prop.Median =True.alpha3.prop_median)
c = c %>% select(True.omega3.value, True.CV,analysis, mean.MLE, True.value.Mean, median.MLE,mean.prop,True.Prop.Mean,
                 median.prop)

cnames = c("True $\\omega_3$", "True CV of SRV", "Method", "Mean MLE $\\alpha_3$", "True $\\alpha_3$", "Median MLE $\\alpha_3$", "Mean prop $\\alpha_3$", "True prop $\\alpha_3$", "Median prop $\\alpha_3$")

e= c %>% arrange(True.omega3.value) %>% filter(True.omega3.value %in% c(1.1,1.5,2,2.5,2.9))
colnames(e) <- cnames
e.xtab = e%>% xtable()
align(e.xtab) = "r|lp{1cm}l|p{1.5cm}p{1.5cm}p{1.5cm}|p{1.5cm}p{1.5cm}p{1.5cm}|"
e.xtab%>% print( include.rownames = F, sanitize.text.function = function(x){x}, scalebox = .75,  add.to.row = add.to.row,tabular.environment = 'longtable', floating = FALSE, type = 'html')
```

```{r graph for alpha3 values, echo = FALSE}

d = c %>% select(True.omega3.value,True.CV, analysis,mean.MLE, True.value.Mean, median.MLE) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+ 
  labs(x = expression("True "*omega[3]), y = expression("Expected "*alpha[3]))+
  scale_color_discrete(name = "Measure", breaks = c("mean.MLE", "True.value.Mean", "median.MLE"), labels = c("Mean MLE", expression("True "*alpha[3]), "Median MLE"))
```

```{r, echo=FALSE}
d = c %>% select(True.omega3.value,True.CV, analysis,mean.prop, True.Prop.Mean, median.prop) %>%
  melt(id.vars = c("True.omega3.value","True.CV", "analysis"))

d  %>%  ggplot(aes(x = True.omega3.value, y = value,color = variable )) +
  geom_point() + geom_smooth()+ facet_grid(True.CV~analysis, scales = "free")+
  labs(x = expression("True "*omega[3]), y = expression("Expected "*alpha[3]*" prop"))+
  scale_color_discrete(name = "Measure", breaks = c("mean.prop", "True.Prop.Mean", "median.prop"), labels = c("Mean prop", expression("True "*alpha[3]*" prop"), "Median prop"))



```


##True CV of SRV versus Expected CV of SRV

The CV of SRV is only calculated for BUSTED+SRV as that is the only method that allows the synonymous rate to vary. 

```{r, echo= FALSE}

CVs = a %>% select(True.omega3.value, True.CV, CV.SRV) %>% group_by(True.omega3.value, True.CV) %>% summarise_at(vars(matches("CV.SRV")), funs(mean,median))


```

```{r, echo = FALSE}
CVs %>% melt(id.vars = c("True.omega3.value","True.CV")) %>% ggplot(aes(x=True.CV, y = value, color = interaction(variable, True.omega3.value)))+geom_point()+geom_abline(slope = 1, intercept = 0)
```

##Tree Length

```{r, echo=FALSE}
 Tree.bias = a %>% group_by(True.CV, True.omega3.value)

 
 # b= Tree.bias %>% gather(key = test, value = estimate, -True.CV, - True.omega3.value)
 # 
 # b =ungroup(b) %>% mutate(analysis = str_extract(b$test,"BUSTED.SRV\\.|BUSTED\\.|True"))
 # b = b %>% arrange(True.CV)
 # b = mutate(b, 
 #            stat = str_extract(b$test,"mean|median"))
 # 
 # #glimpse(b)
 # c = spread(select(b, -test), key = stat, value = estimate)
 # c %>% kable
```

```{r, echo = FALSE}
Tree.bias %>% ggplot(aes(x=BUSTED.treelength, y = BUSTED.SRV.treelength, color = True.CV, size = True.omega3.value)) + geom_point() + geom_abline(intercept = 0, slope = 1)

Tree.bias %>% ggplot(aes(x=BUSTED.treelength, y = BUSTED.SRV.treelength, size = True.CV, color = True.omega3.value)) + geom_point() + geom_abline(intercept = 0, slope = 1)

Tree.bias %>% ggplot(aes(x=BUSTED.treelength, y = BUSTED.SRV.treelength, color = True.CV, size = True.omega3.value)) + geom_point() + geom_abline(intercept = 0, slope = 1) + coord_cartesian(xlim = c(0,25),ylim = c(0,25))


Tree.bias %>% ggplot(aes(x=BUSTED.treelength, y = BUSTED.SRV.treelength, size = True.CV, color = True.omega3.value)) + geom_point() + geom_abline(intercept = 0, slope = 1) + coord_cartesian(xlim = c(0,25),ylim = c(0,25))

Tree.bias %>% ggplot(aes(x=BUSTED.treelength, y = BUSTED.SRV.treelength, color = True.omega3.value)) + geom_point() + geom_abline(intercept = 0, slope = 1) + facet_grid(~True.CV)+ coord_cartesian(xlim = c(0,25),ylim = c(0,25))

Tree.bias %>% ggplot(aes(x=BUSTED.treelength, y = BUSTED.SRV.treelength, color = True.CV)) + geom_point() + geom_abline(intercept = 0, slope = 1) + facet_grid(~True.omega3.value)+ coord_cartesian(xlim = c(0,25),ylim = c(0,25))

```










